#!/bin/bash

#SBATCH --mail-type=none
#SBATCH --job-name="hifiasm_Assembly"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1-00:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8

#load the module
module load hifiasm/0.16.1-GCCcore-10.3.0

hifiasm -o hifiASM_output/ERR11437317.asm \
    reads/Had-6b/ERR11437317.fastq.gz


#awk '/^S/{print ">"$2;print $3}' FILE.gfa > FILE.fa