#!/bin/bash

#SBATCH --mail-type=none
#SBATCH --job-name="LJA_assembly"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1-00:00:00
#SBATCH --mem=64G
#SBATCH --partition=pibu_el8
#SBATCH --output=/data/users/mjacquey/assembly_annotation_course/LJA_output_%j.o

READS_DIR=/data/users/mjacquey/assembly_annotation_course/reads/Had-6b
OUTPUT_DIR=/data/users/mjacquey/assembly_annotation_course/LJA_output
APPTAINER=/containers/apptainer/lja-0.2.sif

mkdir -p ${OUTPUT_DIR}

READS_FILE="${READS_DIR}/ERR11437317.fastq.gz"

apptainer exec \
    --bind ${READS_DIR}:/reads:ro \
    --bind ${OUTPUT_DIR}:/output:rw \
    ${APPTAINER} \
    lja -o /output --reads /reads/ERR11437317.fastq.gz